services:
  - type: web
    name: finance-bot
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && playwright install chromium"
    startCommand: "python Finance_bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BOT_ACCESS_PASSWORD
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
